name: My Test Project CI

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Build and test weather-app
        run: ./mvnw -B clean package

      - name: Build Docker image
        run: docker build -t registryquarkus.azurecr.io/my-test-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push registryquarkus.azurecr.io/my-test-app:${{ github.sha }}
